version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:azurite
    env_file:
      - ../.env

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: unless-stopped
