name: Deploy Node.js project to Azure Function App

on: 
  push:
    branches:
      - initial-commit

# on:
#   pull_request:
#     types: [opened, reopened]
#     branches:
#       - main

env:
  AZURE_FUNCTIONAPP_NAME: 'w2l-prd-uks-fa'   # function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'          # path to function app project, defaults to the repository root
  NODE_VERSION: '18.19.0'                      # node version to use (e.g. '8.x', '10.x', '12.x')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prd
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      # - name: Build and run dev container task
      #   uses: devcontainers/ci@v0.3
      #   with:
      #     # Change this to be your CI task/script
      #     runCmd: |
      #       npm install
      #       npm start
      #       npm test
          
    # steps:
    # - name: 'Checkout GitHub Action'
    #   uses: actions/checkout@v3

    # - name: Setup Node ${{ env.NODE_VERSION }} Environment
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: ${{ env.NODE_VERSION }}

    # - name: 'Resolve Project Dependencies Using Npm'
    #   shell: bash
    #   run: |
    #     pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
    #     npm install
    #     npm run build --if-present
    #     npm run test --if-present
    #     popd

      # - name: 'Login via Azure CLI'
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Resolve Project Dependencies Using Npm'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm install
          popd

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          # publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}