name: Deploy Node.js project to Azure Function App

on: 
  push:
    branches:
      - initial-commit

# on:
#   pull_request:
#     types: [opened, reopened]
#     branches:
#       - main

env:
  AZURE_RESOURCE_GROUP_NAME: 'w2l-prd-uks-rg'  # resource group name on Azure
  AZURE_FUNCTIONAPP_NAME: 'w2l-prd-uks-fa'     # function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'          # path to function app project, defaults to the repository root
  NODE_VERSION: '18.19.0'                      # node version to use (e.g. '8.x', '10.x', '12.x')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prd
    env:
      FunctionName: 'AdaptiveCardTemplateExpansionService'
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Resolve Project Dependencies'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm install
          popd

      - name: 'Deploy Azure Function'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          respect-funcignore: true

      - name: 'Get Function Invocation URL'
        id: get_invocation_url
        shell: bash
        run: |
          INVOKE_URL_BASE=$(az functionapp function show --g $AZURE_RESOURCE_GROUP_NAME --n $AZURE_FUNCTIONAPP_NAME --function-name $FunctionName --query "invokeUrlTemplate" --output tsv)
          FUNCTION_CODE=$(az functionapp function keys list -g $AZURE_RESOURCE_GROUP_NAME -n $AZURE_FUNCTIONAPP_NAME --function-name $FunctionName --query "default" --output tsv)
          echo ${FUNCTION_INVOKE_URL_BASE}?code=${FUNCTION_CODE} >> $FUNCTION_INVOKE_URL

      - name: 'Print Function Invocation URL'
        shell: bash
        run: |
          echo "Function Invocation URL: ${{ steps.get_invocation_url.outputs.FUNCTION_INVOKE_URL }}"
